name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run MailFetch and generate report
      run: |
        python MailFetch.py > output.txt 2>&1

    - name: List files in the directory
      run: ls -la

    - name: Upload output file
      if: always()  # Ensure this step runs even if the previous steps fail
      uses: actions/upload-artifact@v2
      with:
        name: output-file
        path: output.txt

    - name: Upload report artifact
      if: always()  # Ensure this step runs even if the previous steps fail
      uses: actions/upload-artifact@v2
      with:
        name: email-report
        path: email_report.csv
