name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run MailFetch and generate report
      run: |
        python MailFetch.py

    - name: Upload report artifact
      uses: actions/upload-artifact@v2
      with:
        name: email-report
        path: email_report.csv

    - name: Send report via email
      run: |
        python -c "
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import os

def send_email_report(filename, recipient_email):
    sender_email = 'priyankapolasi206@gmail.com'
    sender_password = os.environ.get('EMAIL_PASSWORD')

    message = MIMEMultipart()
    message['From'] = sender_email
    message['To'] = recipient_email
    message['Subject'] = 'Email Report - Malicious and Non-Malicious Emails'

    body = 'Please find attached the report of processed emails.'
    message.attach(MIMEText(body, 'plain'))

    with open(filename, 'rb') as attachment:
        part = MIMEBase('application', 'octet-stream')
        part.set_payload(attachment.read())
        encoders.encode_base64(part)
        part.add_header(
            'Content-Disposition',
            f'attachment; filename= {filename}',
        )
        message.attach(part)

    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login(sender_email, sender_password)
    text = message.as_string()
    server.sendmail(sender_email, recipient_email, text)
    server.quit()

send_email_report('email_report.csv', 'priyankapolasi206@gmail.com')
        "
